---

- name: Retrieve node facts
  hosts: eap1.hpe.lab

- name: Create iSCSI initators for hosts in nodes group
  gather_facts: false
  hosts: nva
  collections:
    - hpe.nimble
  tasks:
    - name: Add host
      hpe_nimble_initiator_group:
        host: "172.30.4.80"
        username: "admin"
        password: "password"
        access_protocol: iscsi
        name: "{{ item }}"
        iscsi_initiators: [
          {
            iqn: "{{ hostvars[item]['ansible_iscsi_iqn'] }}",
            label: "{{ item }}"
          }
        ]
        description: "Initiator Group for {{ item }}"
        state: present
      with_items: "{{ groups.nodes }}"