---
- name: start jboss and deploy war file
  hosts: eap1.hpe.lab

  tasks: 
  
  - name: Extract jboss binary file
    unarchive:
      src: /home/admin/jboss-eap-7.4.0.zip
      dest: /home/admin/
      remote_src: yes

  - name: add admin user
    shell: /home/admin/jboss-eap-7.4/bin/add-user.sh admin password

  - name: run standalone.sh
    shell: nohup /home/admin/jboss-eap-7.4/bin/standalone.sh &

  - name: deploy war file
    synchronize:
      src: /home/admin/Downloads/verify-cluster.war
      dest: /home/admin/jboss-eap-7.4/standalone/deployments/
    delegate_to: ansible.hpe.lab





  

